eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8088

spring:
  application:
    name: user
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/sshop_user
    username: postgres
    password: tiensy002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sshop
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    password: gscr ujds bdrk orjh
    username: ntiensy2002@gmail.com
    properties:
      mail:
      smtp:
        auth: true
        starttls:
          enable: true
application :
  otp:
    secret: BP26TDZUZ5SVPZJRIHCAUVREO5EWMHHV
  notification:
    discount-product-template: 4589bc23-5072-4153-8ed2-5137de2bb38a
    discount-product-event: 6ab8ccf1-b38a-42ca-bfc6-4b2e03c2351d
    purchase-notification-template: 9ecd5d49-669d-49df-b43f-1decbada6611
    purchase-notification-event: fdf2d4cd-15a1-4025-8365-0c94f755ae3e
  config:
    notification-url: http://localhost:8081/api/v1/notification
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3600000
      expiration-refresh: 86400000
  crypto:
    public-file-path:  ./src/main/resources/public.txt
    private-file-path: ./src/main/resources/private.txt
    secret-file-path: ./src/main/resources/secret.txt
    enable: true
  email:
    tracking:
      url: http://localhost:8088/api/v1/email/tracking

